---
abstract: 'Client for the Atlassian Confluence wiki, based on RPC::XML'
author:
  - 'Asgeir Nilsen'
  - 'Giles Lewis'
  - 'Martin Ellis'
  - 'Torben K. Jensen'
  - 'Heiko Jansen <hjansen@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.133380'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Confluence-Client-XMLRPC
requires:
  Carp: 0
  Data::Dumper: 0
  RPC::XML: 0
resources:
  homepage: https://confluence.atlassian.com/display/DISC/Perl+XML-RPC+client
  repository: https://github.com/heikojansen/confluence-client-xmlrpc.git
version: 2.5
